### ISSUE TITLE
Update mavenisation build

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/GPML2RDF#59]
Tried to build the repository in Eclipse, but got some errors, related to libraries that are missing/not part of https://mvnrepository.com/artifact/org.bridgedb/org.bridgedb . 
- [x] bridgedb release
- [x] PV core
- [x] PV-WP client

**Comment by egonw** [comment]
The last two is because they are not in Maven Central. The first is a version issue. You need to compile each one of them locally and then locally install the resulting jar into your local Maven repository:

For BridgeDb 2.3.1 just run the `mvn install` on that source folder.

For PathVisio and WikiPathways client which do not use Maven, you need to use something like this:

```shell
mvn install:install-file -Dfile=pathvisio.jar -DgroupId=org.pathvisio -DartifactId=pathvisio-core -Dversion=3.3.0 -Dpackaging=jar
mvn install:install-file -Dfile=lib/wikipathways-client-3.2.1.wprdf.jar -DgroupId=org.pathvisio -DartifactId=wikipathways-client -Dversion=3.2.1.wprdf -Dpackaging=jar
```
