### ISSUE TITLE
Missing annotations for reactome pathways in RDF

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/GPML2RDF#76]
I found Reactome pathways that are missing the triple in the RDF:
Pathway     wp:ontologyTag     <http://vocabularies.wikipathways.org/wp#Curation:Reactome_Approved> 

An example:  <http://identifiers.org/wikipathways/WP3397_r101273>

**Comment by egonw** [comment]
Seems to be there now:

![image](https://user-images.githubusercontent.com/26721/111031948-4fe6d780-840a-11eb-978a-8e4c1fc0d34a.png)

So, we know that the RDF creating of the triples works.

What I do not know, if the tag gets included if the latest version is not approved, but then again, it probably should not, because that version is not approved.
